name: history_manager
description: Simple & Efficient history tracker dart mixin.
version: 1.3.0
homepage:
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  nampack:
    git:
      url: https://github.com/MSOB7YY/nampack
  dart_extensions:
    git:
      url: https://github.com/MSOB7YY/dart_extensions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  obx_lints:
    git:
      url: https://github.com/MSOB7YY/nampack
      path: packages/obx_lints

flutter:
